name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create google-services.json
        env:
          FIREBASE_SERVICE_JSON: ${{ secrets.FIREBASE_SERVICE_JSON }}
        run: echo "$FIREBASE_SERVICE_JSON" > ./app/google-services.json

      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Run unit tests
        run: ./gradlew test --info

  emulator-setup:
    needs: build-and-test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create google-services.json
        env:
          FIREBASE_SERVICE_JSON: ${{ secrets.FIREBASE_SERVICE_JSON }}
        run: echo "$FIREBASE_SERVICE_JSON" > ./app/google-services.json

      - name: Cache Android emulator system images
        uses: actions/cache@v3
        with:
          path: |
            ~/.android/cache/
          key: ${{ runner.os }}-android-emulator-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-emulator-cache-

      - name: Add avdmanager and sdkmanager to system PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH

      - name: Install Sdk
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "system-images;android-34;google_apis_playstore;x86_64" "platforms;android-34" "build-tools;34.0.0" "platform-tools" "emulator"

      - name: Pre-launch emulator
        run: |
          echo "no" | avdmanager --verbose create avd --force -n emulator -k "system-images;android-34;google_apis_playstore;x86_64" --abi google_apis_playstore/x86_64 --device "pixel"
          chmod +x ./.github/start_emu_headless.sh && ./.github/start_emu_headless.sh prelaunch

      - name: Wait for emulator to be fully ready
        run: sleep 30

      - name: Run tests with debug information
        run: |
          chmod +x ./.github/start_emu_headless.sh && ./.github/start_emu_headless.sh postlaunch
          ./gradlew connectedAndroidTest --info

      - name: Capture emulator logs
        if: failure()
        run: adb logcat -d > emulator_logcat.txt

      - name: Upload emulator logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: emulator-logs
          path: emulator_logcat.txt
