name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Create google-services.json
      env:
        FIREBASE_SERVICE_JSON: ${{ secrets.FIREBASE_SERVICE_JSON }}
      run: |
        echo "$FIREBASE_SERVICE_JSON" > ./app/google-services.json
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run unit tests
      run: ./gradlew test

      # Setup Android Emulator and run instrumented tests
    - name: Run instrumented tests on Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 34  # Use the required API level here
        target: google_apis
        arch: x86_64   # Use the required architecture here
        profile: Nexus 6
        script: |
            ./gradlew connectedCheck --stacktrace
